speaker:
  default_param:
    robot_ip: "192.168.1.101" #include the IP of the robot
    instance_id : "furhat"
    mockup: 0
  furhat_param:
    robot_ip: "192.168.1.101" #include the IP of the Furhat robot
    instance_id : "furhat"
    mockup: 0
  nao_param:
    robot_ip: "192.168.1.100" #include the IP of the Nao robot
    instance_id : "nao"
    mockup: 0

