# Configuration file for the dialogue
bot:
  default_param:
    user_id: "Micol"
    bot_name: "QTRobot"
    bot_alias: "DemoBot"
    region_name: "eu-west-2"
    assistant_id: "asst_IGcxRcdHHQptkIbpp7wsbCLv" #ORACLE
    service_id : "default"
  mover_param:
    assistant_id: "asst_1rkI7oi5Kz811ZERcPd19zFj" #MOVER
    service_id : "mover"
  opposer_param:
    assistant_id: "asst_oaDSHB0jluXcVC2cAwNx83oS" #OPPOSER
    service_id : "opposer"


google:
  default_param:
    project_id: "agent1-ewhnht"
    language: "it"
    session_id: "test_bot"
    credential_path: "$(env HOME)/.gcp/private-keys.json/private-keys.json" #path where private keys are mounted


chat_gpt:
  default_param:
    model: "gpt-4o-mini"
  mover_param:
    model: "gpt-4o-mini"
    assistant_id: "asst_1rkI7oi5Kz811ZERcPd19zFj" #MOVER
    service_id : "mover"
  opposer_param:
    model: "gpt-4o-mini"
    assistant_id: "asst_oaDSHB0jluXcVC2cAwNx83oS" #OPPOSER
    service_id : "opposer"
    

assistant:
  default_param:
    assistant_id: "asst_IGcxRcdHHQptkIbpp7wsbCLv" #ORACLE
    service_id : "default"
  mover_param:
    assistant_id: "asst_1rkI7oi5Kz811ZERcPd19zFj" #MOVER
    service_id : "mover"
  opposer_param:
    assistant_id: "asst_oaDSHB0jluXcVC2cAwNx83oS" #OPPOSER
    service_id : "opposer"
    